import * as vscode from 'vscode';
import { ProjectBrainCore } from '@projectbrain/core';

let core: ProjectBrainCore | undefined;

export function activate(context: vscode.ExtensionContext) {
  const workspaceFolders = vscode.workspace.workspaceFolders;
  const rootPath = workspaceFolders && workspaceFolders.length > 0 ? workspaceFolders[0].uri.fsPath : process.cwd();

  core = new ProjectBrainCore({
    rootPath,
    config: {
      analysis: {
        include: ['src/**'],
        exclude: ['node_modules/**', 'dist/**']
      },
      ai: {
        mode: 'offline'
      },
      rules: {
        autoGenerate: true
      }
    }
  });

  // Register command: Analyze
  const analyzeCmd = vscode.commands.registerCommand('projectbrain.analyze', async () => {
    vscode.window.showInformationMessage('ProjectBrain: Analyzing codebase...');
    await core?.scanAndIndex();
    const score = core?.calculateHealthScore();
    vscode.window.showInformationMessage(`ProjectBrain: Analysis complete. Health score: ${score?.overall}/100`);
  });

  // Register command: Find Dead Code
  const deadCodeCmd = vscode.commands.registerCommand('projectbrain.findDeadCode', async () => {
    const deadCodeItems = core?.findDeadCode() ?? [];
    if (deadCodeItems.length === 0) {
      vscode.window.showInformationMessage('ProjectBrain: No dead code detected.');
    } else {
      vscode.window.showWarningMessage(`ProjectBrain: Found ${deadCodeItems.length} potentially unused code items.`);
    }
  });

  // Register command: Generate AI Prompt
  const generatePromptCmd = vscode.commands.registerCommand('projectbrain.generatePrompt', async () => {
    const task = await vscode.window.showInputBox({
      prompt: 'Enter task description for AI Prompt Generation',
      placeHolder: 'e.g. Implement user notifications'
    });

    if (!task) return;

    const prompt = core?.promptBuilder.buildMarkdownPrompt({
      task,
      projectOverview: 'Project overview generated by ProjectBrain.',
      relevantFiles: [],
      relevantSymbols: [],
      architectureOverview: 'Architecture layers identified.',
      existingImplementations: [],
      projectConventions: [],
      knownProblems: [],
      doNotDuplicate: [],
      taskBoundaryNotice: 'Previous task context is not authoritative. Start from current project state.',
      instructionsForAi: [
        'Follow existing architecture and conventions.',
        'Do not duplicate existing utility functions.',
        'Ensure type safety and no unused exports.'
      ]
    });

    if (prompt) {
      await vscode.env.clipboard.writeText(prompt);
      vscode.window.showInformationMessage('ProjectBrain: Context prompt copied to clipboard!');
    }
  });

  // Register command: Start Task Session
  const startTaskCmd = vscode.commands.registerCommand('projectbrain.startTask', async () => {
    const title = await vscode.window.showInputBox({
      prompt: 'Enter task name to start session',
      placeHolder: 'e.g. Refactor auth service'
    });
    if (!title) return;

    const session = core?.startTaskSession(`task-${Date.now()}`, title);
    vscode.window.showInformationMessage(`ProjectBrain: Started task session [${session?.title}]`);
  });

  // Register command: Finish Task Session
  const finishTaskCmd = vscode.commands.registerCommand('projectbrain.finishTask', () => {
    core?.finishTaskSession();
    vscode.window.showInformationMessage('ProjectBrain: Task session finished.');
  });

  // Register command: Review AI Changes
  const reviewCmd = vscode.commands.registerCommand('projectbrain.reviewAiChanges', () => {
    vscode.window.showInformationMessage('ProjectBrain: Reviewing AI changes...');
  });

  context.subscriptions.push(
    analyzeCmd,
    deadCodeCmd,
    generatePromptCmd,
    startTaskCmd,
    finishTaskCmd,
    reviewCmd
  );
}

export function deactivate() {
  core = undefined;
}
